### ISSUE TITLE
Thermal Expansion silver ore lit at wrong value

### ISSUE THREAD

**Issue by Compegen** [PersonTheCat/OreStoneVariants#73]
The silver ore replacement has a light level of 14, where the normal ore has light level 4
![2019-08-15_16 49 21](https://user-images.githubusercontent.com/8009507/63129483-3e62f280-bf7d-11e9-9975-f5acbcaf78ce.png)

**Comment by PersonTheCat** [comment]
This seems to have been a bug with all light values being set too high when background imitation is disabled. I have fixed that in 4.6, which will be uploaded by the end of the night and should get approved by Monday.

**Comment by Compegen** [comment]
This is still an issue as of 4.6
![2020-03-22_16 57 41](https://user-images.githubusercontent.com/8009507/77261701-51018080-6c5e-11ea-92e3-01ac26103864.png)

**Comment by PersonTheCat** [comment]
I'll check this again in 5.1 and verify it's been fixed.
